"DbUser" = "postgres@postgresdbmoe"
"DbPassword" = "XCdfER43CDxvd"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "postgresdbmoe.postgres.database.azure.com"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"